name = "GenomicFeatureVectors"
uuid = "d3dd2677-0723-41d4-8eab-c60ffbbcb51f"
authors = ["Aaron Lun <lun.aaron@gene.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GenomicFeatures = "899a7d2d-5c61-547b-bef9-6698a8d05446"
